-- P1.2 — Tenant columns and composite uniques.
--
-- This file was generated by drizzle-kit and then REWRITTEN BY HAND, because the generated
-- form is only correct against an empty database.
--
-- What was wrong with the generated version
-- -----------------------------------------
-- It emitted fourteen statements of the form:
--
--     ALTER TABLE "messages" ADD COLUMN "organization_id" varchar(255) NOT NULL;
--
-- PostgreSQL rejects that outright on any table that already has rows: there is no default,
-- so the existing rows would violate NOT NULL immediately. Against the current (unprovisioned)
-- database it would have appeared to work, and it would have failed the first time it met real
-- data — which is exactly the class of "it compiled, therefore it works" this project is trying
-- to stop shipping.
--
-- What this version does instead
-- ------------------------------
-- The standard three phases: add the column nullable, backfill it, then enforce NOT NULL.
--
-- The backfill derives each row's tenant from its parent, so no row is assigned to a tenant on
-- the strength of a guess. Four tables have no parent to derive from — campaigns,
-- knowledge_items, attention_items and ai_run_logs — and for those the migration DELIBERATELY
-- STOPS and tells the operator to supply the value, rather than sweeping the rows into whatever
-- organisation happens to be first. Assigning a customer record to the wrong tenant is not a
-- lesser failure than aborting a migration.
--
-- Adding the uniques may also fail, and that failure is INFORMATION: it means duplicates
-- already exist that the missing constraints permitted. Resolve them before re-running; do not
-- weaken the constraint to make the migration pass.
--
-- Set the fallback organisation before running, if the parentless tables have rows:
--     \set migration_org_id 'your-org-id'
-- or edit the DO block below.

-- ---------------------------------------------------------------------------
-- 1. New table (no backfill needed).
-- ---------------------------------------------------------------------------
CREATE TABLE "campaign_recipients" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"organization_id" varchar(255) NOT NULL,
	"campaign_id" varchar(255) NOT NULL,
	"contact_id" varchar(255) NOT NULL,
	"step_number" integer DEFAULT 0 NOT NULL,
	"status" varchar(50) DEFAULT 'ENROLLED' NOT NULL,
	"last_step_sent_at" timestamp,
	"next_step_due_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "campaign_recipients_org_campaign_contact_unique" UNIQUE("organization_id","campaign_id","contact_id")
);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. Drop the global uniques that tenancy replaces.
--
--    users.email was globally unique, which stops one person holding an account in two
--    organisations and turns "is this address taken?" into a probe for users in someone else's
--    tenant. outbox_messages.idempotency_key was globally unique, so one tenant's key could
--    suppress another tenant's send — a silent non-delivery that looks like deduplication.
-- ---------------------------------------------------------------------------
ALTER TABLE "outbox_messages" DROP CONSTRAINT IF EXISTS "outbox_messages_idempotency_key_unique";--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_unique";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. Add the columns NULLABLE.
-- ---------------------------------------------------------------------------
ALTER TABLE "ai_run_logs" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "attention_items" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "email_key" varchar(255);--> statement-breakpoint
ALTER TABLE "conversation_facts" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "customer_commitments" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "knowledge_items" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "meetings" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "objection_ledger" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "opportunities" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "outbox_messages" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "question_ledger" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint
ALTER TABLE "quote_snapshots" ADD COLUMN "organization_id" varchar(255);--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. Backfill from the parent row.
--
--    Each row's tenant is the tenant of the record it already belongs to. Nothing here
--    invents an association.
--
--    contacts.email_key mirrors server/lib/emailKey.ts: the address is taken out of any
--    display-name form, trimmed and lowercased. If the two ever disagree the constraint stops
--    meaning what it says, so they are changed together.
-- ---------------------------------------------------------------------------
UPDATE "contacts"
   SET "email_key" = lower(trim(
         CASE WHEN "primary_email" LIKE '%<%>%'
              THEN substring("primary_email" from '<([^<>]+)>')
              ELSE "primary_email"
         END))
 WHERE "email_key" IS NULL;--> statement-breakpoint

UPDATE "messages" m
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE m."conversation_id" = c."id" AND m."organization_id" IS NULL;--> statement-breakpoint

UPDATE "conversation_facts" f
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE f."conversation_id" = c."id" AND f."organization_id" IS NULL;--> statement-breakpoint

UPDATE "outbox_messages" o
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE o."conversation_id" = c."id" AND o."organization_id" IS NULL;--> statement-breakpoint

UPDATE "customer_commitments" x
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE x."conversation_id" = c."id" AND x."organization_id" IS NULL;--> statement-breakpoint

UPDATE "question_ledger" x
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE x."conversation_id" = c."id" AND x."organization_id" IS NULL;--> statement-breakpoint

UPDATE "objection_ledger" x
   SET "organization_id" = c."organization_id"
  FROM "conversations" c
 WHERE x."conversation_id" = c."id" AND x."organization_id" IS NULL;--> statement-breakpoint

UPDATE "meetings" m
   SET "organization_id" = c."organization_id"
  FROM "contacts" c
 WHERE m."contact_id" = c."id" AND m."organization_id" IS NULL;--> statement-breakpoint

UPDATE "opportunities" o
   SET "organization_id" = c."organization_id"
  FROM "contacts" c
 WHERE o."contact_id" = c."id" AND o."organization_id" IS NULL;--> statement-breakpoint

UPDATE "quote_snapshots" q
   SET "organization_id" = c."organization_id"
  FROM "contacts" c
 WHERE q."contact_id" = c."id" AND q."organization_id" IS NULL;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. Refuse to guess.
--
--    campaigns, knowledge_items, attention_items and ai_run_logs have no parent that names a
--    tenant. If any of them holds rows, this migration stops. That is the intended behaviour:
--    the alternative is to assign one customer's campaign, knowledge or audit log to another
--    customer's organisation, silently and irreversibly, and a failed migration is recoverable
--    in a way that is not.
--
--    To proceed, set the organisation these rows belong to and re-run:
--        UPDATE campaigns SET organization_id = '<org>' WHERE organization_id IS NULL;
--    (likewise for knowledge_items, attention_items, ai_run_logs)
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  orphans record;
  total bigint := 0;
  detail text := '';
BEGIN
  FOR orphans IN
    SELECT 'campaigns' AS t, count(*) AS n FROM campaigns WHERE organization_id IS NULL
    UNION ALL SELECT 'knowledge_items', count(*) FROM knowledge_items WHERE organization_id IS NULL
    UNION ALL SELECT 'attention_items', count(*) FROM attention_items WHERE organization_id IS NULL
    UNION ALL SELECT 'ai_run_logs', count(*) FROM ai_run_logs WHERE organization_id IS NULL
    UNION ALL SELECT 'messages (orphaned)', count(*) FROM messages WHERE organization_id IS NULL
    UNION ALL SELECT 'conversation_facts (orphaned)', count(*) FROM conversation_facts WHERE organization_id IS NULL
    UNION ALL SELECT 'outbox_messages (orphaned)', count(*) FROM outbox_messages WHERE organization_id IS NULL
    UNION ALL SELECT 'meetings (orphaned)', count(*) FROM meetings WHERE organization_id IS NULL
    UNION ALL SELECT 'opportunities (orphaned)', count(*) FROM opportunities WHERE organization_id IS NULL
    UNION ALL SELECT 'quote_snapshots (orphaned)', count(*) FROM quote_snapshots WHERE organization_id IS NULL
    UNION ALL SELECT 'customer_commitments (orphaned)', count(*) FROM customer_commitments WHERE organization_id IS NULL
    UNION ALL SELECT 'question_ledger (orphaned)', count(*) FROM question_ledger WHERE organization_id IS NULL
    UNION ALL SELECT 'objection_ledger (orphaned)', count(*) FROM objection_ledger WHERE organization_id IS NULL
    UNION ALL SELECT 'contacts (no usable email)', count(*) FROM contacts WHERE email_key IS NULL
  LOOP
    IF orphans.n > 0 THEN
      total := total + orphans.n;
      detail := detail || format('  %s: %s row(s)%s', orphans.t, orphans.n, chr(10));
    END IF;
  END LOOP;

  IF total > 0 THEN
    RAISE EXCEPTION
      'P1.2 migration stopped: % row(s) have no derivable tenant.%s%sAssign them explicitly and re-run. Do NOT default them to an arbitrary organisation.',
      total, chr(10), detail;
  END IF;
END $$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. Enforce NOT NULL now that every row has a value.
-- ---------------------------------------------------------------------------
ALTER TABLE "ai_run_logs" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "attention_items" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "campaigns" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "email_key" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conversation_facts" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "customer_commitments" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_items" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "meetings" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "objection_ledger" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "opportunities" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "outbox_messages" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "question_ledger" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quote_snapshots" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 7. Foreign keys.
-- ---------------------------------------------------------------------------
ALTER TABLE "campaign_recipients" ADD CONSTRAINT "campaign_recipients_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_recipients" ADD CONSTRAINT "campaign_recipients_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_recipients" ADD CONSTRAINT "campaign_recipients_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_run_logs" ADD CONSTRAINT "ai_run_logs_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attention_items" ADD CONSTRAINT "attention_items_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation_facts" ADD CONSTRAINT "conversation_facts_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_commitments" ADD CONSTRAINT "customer_commitments_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_items" ADD CONSTRAINT "knowledge_items_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "objection_ledger" ADD CONSTRAINT "objection_ledger_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outbox_messages" ADD CONSTRAINT "outbox_messages_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "question_ledger" ADD CONSTRAINT "question_ledger_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quote_snapshots" ADD CONSTRAINT "quote_snapshots_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 8. Indexes.
-- ---------------------------------------------------------------------------
CREATE INDEX "campaign_recipients_due_idx" ON "campaign_recipients" USING btree ("organization_id","status","next_step_due_at");--> statement-breakpoint
CREATE INDEX "accounts_org_idx" ON "accounts" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "ai_run_logs_org_idx" ON "ai_run_logs" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX "attention_items_org_idx" ON "attention_items" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "campaigns_org_idx" ON "campaigns" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "contacts_org_idx" ON "contacts" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "conversation_facts_org_conversation_idx" ON "conversation_facts" USING btree ("organization_id","conversation_id");--> statement-breakpoint
CREATE INDEX "conversations_org_idx" ON "conversations" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "customer_commitments_org_conversation_idx" ON "customer_commitments" USING btree ("organization_id","conversation_id");--> statement-breakpoint
CREATE INDEX "knowledge_items_org_idx" ON "knowledge_items" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "meetings_org_scheduled_idx" ON "meetings" USING btree ("organization_id","scheduled_time");--> statement-breakpoint
CREATE INDEX "messages_org_conversation_idx" ON "messages" USING btree ("organization_id","conversation_id");--> statement-breakpoint
CREATE INDEX "objection_ledger_org_conversation_idx" ON "objection_ledger" USING btree ("organization_id","conversation_id");--> statement-breakpoint
CREATE INDEX "opportunities_org_idx" ON "opportunities" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "outbox_org_status_idx" ON "outbox_messages" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "question_ledger_org_conversation_idx" ON "question_ledger" USING btree ("organization_id","conversation_id");--> statement-breakpoint
CREATE INDEX "quote_snapshots_org_contact_idx" ON "quote_snapshots" USING btree ("organization_id","contact_id");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 9. The five required composite uniques, plus the two that tenancy rescoped.
--
--    A failure here is a finding, not an obstacle: it means the data already contains
--    duplicates that the absence of these constraints permitted — two contacts for one
--    person, one thread split across two conversations, an email ingested twice. Resolve the
--    duplicates; do not drop the constraint.
-- ---------------------------------------------------------------------------
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_org_email_key_unique" UNIQUE("organization_id","email_key");--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_org_thread_unique" UNIQUE("organization_id","provider_thread_id");--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_org_provider_msg_unique" UNIQUE("organization_id","provider","provider_message_id");--> statement-breakpoint
ALTER TABLE "oauth_connections" ADD CONSTRAINT "oauth_org_provider_account_unique" UNIQUE("organization_id","provider","account_email");--> statement-breakpoint
ALTER TABLE "outbox_messages" ADD CONSTRAINT "outbox_org_idempotency_unique" UNIQUE("organization_id","idempotency_key");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_org_email_unique" UNIQUE("organization_id","email");
