import { Router } from 'express';
import { readFileSync } from 'node:fs';
import { sendCaught, sendError } from '../lib/errors.ts';
import { OPENAPI_DOCUMENT_PATH } from '../build/openapi.ts';

/**
 * S11 — the API described by the server that serves it.
 *
 * The document is GENERATED from the route table and the contract registry and COMMITTED at
 * docs/production/openapi.json; the suite regenerates it and refuses drift. This route serves the
 * committed copy. It does not regenerate on request: the bundled server (dist/server.cjs) carries
 * no source for the route table to read, and a document assembled from whatever happened to be
 * on disk would be a description of the wrong thing. A deployment that did not ship the file gets
 * a 503 that says so, not an empty document that reads as "no routes".
 */
export const openapiRouter = Router();

openapiRouter.get('/', (req, res) => {
  try {
    let text: string;
    try {
      text = readFileSync(OPENAPI_DOCUMENT_PATH, 'utf8');
    } catch {
      return sendError(
        req,
        res,
        'CONFIGURATION_ERROR',
        `The OpenAPI document is not present in this deployment (${OPENAPI_DOCUMENT_PATH}). It is generated by npm run openapi and committed.`,
        { status: 503 }
      );
    }
    res.type('application/json').send(text);
  } catch (e) {
    sendCaught(req, res, e);
  }
});
