export enum EmailStatus {
  DRAFT = 'DRAFT',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  APPROVED = 'APPROVED',
  QUEUED = 'QUEUED',
  PROVIDER_ACCEPTED = 'PROVIDER_ACCEPTED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  BOUNCED = 'BOUNCED',
  COMPLAINED = 'COMPLAINED',
  FAILED = 'FAILED',
  REPLIED = 'REPLIED',
  SUPPRESSED = 'SUPPRESSED',
  CANCELLED = 'CANCELLED'
}

export enum MeetingStatus {
  PROPOSED = 'PROPOSED',
  PENDING_CLIENT_CONFIRMATION = 'PENDING_CLIENT_CONFIRMATION',
  PENDING_CALENDAR_CREATION = 'PENDING_CALENDAR_CREATION',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW'
}

export enum PaymentStatus {
  NOT_STARTED = 'NOT_STARTED',
  CHECKOUT_CREATED = 'CHECKOUT_CREATED',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  SENT_FOR_SIGNATURE = 'SENT_FOR_SIGNATURE',
  VIEWED = 'VIEWED',
  SIGNED = 'SIGNED',
  DECLINED = 'DECLINED',
  VOIDED = 'VOIDED'
}

export enum BuyingStage {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  REPLIED = 'REPLIED',
  PROBLEM_AWARE = 'PROBLEM_AWARE',
  DISCOVERY = 'DISCOVERY',
  SOLUTION_EXPLORING = 'SOLUTION_EXPLORING',
  PRODUCT_EVALUATING = 'PRODUCT_EVALUATING',
  TECHNICAL_EVALUATION = 'TECHNICAL_EVALUATION',
  SECURITY_REVIEW = 'SECURITY_REVIEW',
  COMMERCIAL_EVALUATION = 'COMMERCIAL_EVALUATION',
  DEMO_READY = 'DEMO_READY',
  DEMO_BOOKED = 'DEMO_BOOKED',
  TRIAL_EVALUATION = 'TRIAL_EVALUATION',
  BUYING_INTENT = 'BUYING_INTENT',
  PURCHASE_READY = 'PURCHASE_READY',
  NEGOTIATION = 'NEGOTIATION',
  CONTRACTING = 'CONTRACTING',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ONBOARDING = 'ONBOARDING',
  CUSTOMER = 'CUSTOMER',
  FOLLOW_UP_LATER = 'FOLLOW_UP_LATER',
  NOT_INTERESTED = 'NOT_INTERESTED',
  UNSUBSCRIBED = 'UNSUBSCRIBED',
  CLOSED_LOST = 'CLOSED_LOST'
}

export enum MessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND'
}

export enum NextBestAction {
  ANSWER_ONLY = 'ANSWER_ONLY',
  ANSWER_AND_QUALIFY = 'ANSWER_AND_QUALIFY',
  ASK_ONE_CLARIFYING_QUESTION = 'ASK_ONE_CLARIFYING_QUESTION',
  PROVIDE_TECHNICAL_INFORMATION = 'PROVIDE_TECHNICAL_INFORMATION',
  PROVIDE_PRICING = 'PROVIDE_PRICING',
  PREPARE_CUSTOM_QUOTE = 'PREPARE_CUSTOM_QUOTE',
  HANDLE_OBJECTION = 'HANDLE_OBJECTION',
  PROVIDE_CASE_STUDY = 'PROVIDE_CASE_STUDY',
  PROVIDE_DOCUMENT = 'PROVIDE_DOCUMENT',
  OFFER_DEMO = 'OFFER_DEMO',
  OFFER_MEETING = 'OFFER_MEETING',
  SEND_BOOKING_LINK = 'SEND_BOOKING_LINK',
  CREATE_CONFIRMED_MEETING = 'CREATE_CONFIRMED_MEETING',
  REQUEST_HUMAN_REVIEW = 'REQUEST_HUMAN_REVIEW',
  REQUEST_FOUNDER_REVIEW = 'REQUEST_FOUNDER_REVIEW',
  START_TRIAL = 'START_TRIAL',
  START_ONBOARDING = 'START_ONBOARDING',
  SEND_AGREEMENT = 'SEND_AGREEMENT',
  SEND_PAYMENT_LINK = 'SEND_PAYMENT_LINK',
  WAIT = 'WAIT',
  FOLLOW_UP_LATER = 'FOLLOW_UP_LATER',
  CLOSE_LOST = 'CLOSE_LOST',
  SUPPRESS = 'SUPPRESS',
  NO_REPLY = 'NO_REPLY'
}
